responseDto={
    "status": "OK",
    "request_id": "ac6fd09d-ef36-4bdf-84bb-ae1ee12eb518",
    "parameters": {
        "query": "cloths for man",
        "country": "IN",
        "sort_by": "BEST_SELLERS",
        "page": 2
    },
    "data": {
        "total_products": 45866,
        "country": "IN",
        "domain": "www.amazon.in",
        "products": [
            {
                "asin": "B0CZDY1ZKX",
                "product_title": "Boldfit Sports T Shirt for Men Quick Dry Fit Tshirt for Men Gym T Shirts for Men for Casual Wear Workout T Shirts for Man Active Gym Wear for Men Running T-Shirts for Men T Shirt for Man",
                "product_price": "₹399",
                "product_original_price": "₹999",
                "currency": "INR",
                "product_star_rating": "4.8",
                "product_num_ratings": 74,
                "product_url": "https://www.amazon.in/dp/B0CZDY1ZKX",
                "product_photo": "https://m.media-amazon.com/images/I/61zfo184NoL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹399",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B0CTSYFYZC",
                "product_title": "Lymio Men Loose Fit Jeans || Men Jeans Pants || Denim Loose Fit Jeans || Baggy Loose Fit Jeans For Men (Loose Fit Jeans-04-05)",
                "product_price": "₹799",
                "product_original_price": "₹5,999",
                "currency": "INR",
                "product_star_rating": "3.9",
                "product_num_ratings": 943,
                "product_url": "https://www.amazon.in/dp/B0CTSYFYZC",
                "product_photo": "https://m.media-amazon.com/images/I/71gHEC8+QJL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹799",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "400+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B00W04QGDE",
                "product_title": "Jockey Men&#x27;s Regular Fit Racer Back Shirt",
                "product_price": "₹339",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.2",
                "product_num_ratings": 8879,
                "product_url": "https://www.amazon.in/dp/B00W04QGDE",
                "product_photo": "https://m.media-amazon.com/images/I/716sMYZu12L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹339",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "300+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B07XKZF6V5",
                "product_title": "adidas Men&#x27;s Regular Fit T-Shirt",
                "product_price": "₹749",
                "product_original_price": "₹1,299",
                "currency": "INR",
                "product_star_rating": "4",
                "product_num_ratings": 1658,
                "product_url": "https://www.amazon.in/dp/B07XKZF6V5",
                "product_photo": "https://m.media-amazon.com/images/I/71OVyMQ3w0S._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹749",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B0B51712RR",
                "product_title": "KETCH Men Slim Fit Checked Full Sleeve Shirt",
                "product_price": "₹358",
                "product_original_price": "₹899",
                "currency": "INR",
                "product_star_rating": "3.8",
                "product_num_ratings": 257,
                "product_url": "https://www.amazon.in/dp/B0B51712RR",
                "product_photo": "https://m.media-amazon.com/images/I/91cAPJCQG8L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹358",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "300+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B0CRPH1PPT",
                "product_title": "Lymio Casual Shirt for Men|| Shirt for Men|| Men Stylish Shirt (Rib-Shirt)",
                "product_price": "₹479",
                "product_original_price": "₹3,999",
                "currency": "INR",
                "product_star_rating": "3.9",
                "product_num_ratings": 1190,
                "product_url": "https://www.amazon.in/dp/B0CRPH1PPT",
                "product_photo": "https://m.media-amazon.com/images/I/71gxzNP0V3L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹479",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "300+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B0855PC4RR",
                "product_title": "JUGULAR Men&#x27;s Cotton Solid Men Stylish Cargo Black Track Pants",
                "product_price": "₹479",
                "product_original_price": "₹1,399",
                "currency": "INR",
                "product_star_rating": "3.7",
                "product_num_ratings": 7749,
                "product_url": "https://www.amazon.in/dp/B0855PC4RR",
                "product_photo": "https://m.media-amazon.com/images/I/71r3RWbLWAL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹479",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B0CLZX5FX4",
                "product_title": "GRECIILOOKS Men&#x27;s Regular Fit Shirt",
                "product_price": "₹484",
                "product_original_price": "₹2,499",
                "currency": "INR",
                "product_star_rating": "4",
                "product_num_ratings": 1007,
                "product_url": "https://www.amazon.in/dp/B0CLZX5FX4",
                "product_photo": "https://m.media-amazon.com/images/I/71QrkXBPABL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹484",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "M.R.P: ",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B08SVVQB1H",
                "product_title": "CBlue Men&#x27;s Outdoor Quick Dry Lightweight Sports Shorts 2 Zipper Pockets",
                "product_price": "₹469",
                "product_original_price": "₹999",
                "currency": "INR",
                "product_star_rating": "3.6",
                "product_num_ratings": 7076,
                "product_url": "https://www.amazon.in/dp/B08SVVQB1H",
                "product_photo": "https://m.media-amazon.com/images/I/71nbQOeQktL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹469",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "M.R.P: ",
                "delivery": "FREE Delivery by Amazon",
                "coupon_text": "Save 2% with coupon (limited sizes/colours)",
                "has_variations": true
            },
            {
                "asin": "B0BV71H3CF",
                "product_title": "TOPLOT Men&#x27;s Regular Fit Causal Trouser",
                "product_price": "₹499",
                "product_original_price": "₹2,599",
                "currency": "INR",
                "product_star_rating": "3.9",
                "product_num_ratings": 1821,
                "product_url": "https://www.amazon.in/dp/B0BV71H3CF",
                "product_photo": "https://m.media-amazon.com/images/I/51JvyNGP6xL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹499",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "300+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B0922G6316",
                "product_title": "ZEEL Rain Coat for Men Waterproof for Bike Riders with Adjustable Hood along with inner pockets,Waterproof Double Layered Rainwear Suit with Polyester Jacket,Pants and Carrying Pouch,ZT5",
                "product_price": "₹1,999",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "3.7",
                "product_num_ratings": 1829,
                "product_url": "https://www.amazon.in/dp/B0922G6316",
                "product_photo": "https://m.media-amazon.com/images/I/51EV-mQc3PL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹1,999",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "Get it by Friday 2 AugustFREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B0C8V2KQCR",
                "product_title": "London Hills Men&#x27;s Casual Printed Round Neck, Oversized Longline Drop Shoulder Boho Style T-Shirt",
                "product_price": "₹283",
                "product_original_price": "₹1,299",
                "currency": "INR",
                "product_star_rating": "3.7",
                "product_num_ratings": 1064,
                "product_url": "https://www.amazon.in/dp/B0C8V2KQCR",
                "product_photo": "https://m.media-amazon.com/images/I/61S5nUPVufL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹283",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "300+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B00W05KORM",
                "product_title": "Jockey 9500 Men&#x27;s Super Combed Cotton Rich Regular Fit Trackpants with Side Pockets",
                "product_price": "₹999",
                "product_original_price": null,
                "currency": "INR",
                "product_star_rating": "4.2",
                "product_num_ratings": 7759,
                "product_url": "https://www.amazon.in/dp/B00W05KORM",
                "product_photo": "https://m.media-amazon.com/images/I/61xidlWeNhL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹999",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B0CS2T4XM2",
                "product_title": "Veirdo Oversized Baggy Fit Drop Shoulder Half Sleeves Round Neck Solid Pure 100% Cotton T-Shirt for Men (Available in White, Black, Mustard, Maroon, Green, Lilac, Navy, Red Color)",
                "product_price": "₹329",
                "product_original_price": "₹1,099",
                "currency": "INR",
                "product_star_rating": "4",
                "product_num_ratings": 496,
                "product_url": "https://www.amazon.in/dp/B0CS2T4XM2",
                "product_photo": "https://m.media-amazon.com/images/I/511kgCPI5eL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹329",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B0CV79B8G5",
                "product_title": "LEOTUDE Regular Fit Half Sleeve Round Neck Dri-Fit Tshirt for Men&#x27;s Combo (Pack of 3)",
                "product_price": "₹498",
                "product_original_price": "₹1,099",
                "currency": "INR",
                "product_star_rating": "3.9",
                "product_num_ratings": 403,
                "product_url": "https://www.amazon.in/dp/B0CV79B8G5",
                "product_photo": "https://m.media-amazon.com/images/I/61ThK8RnMjL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹498",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B072NBHL7K",
                "product_title": "Lux Cozi Men&#x27;s Round Neck Sleeveless 100% Cotton Vest with Extended Length for Easy Tuck - Pack of 3 (Color &amp; Prints May Vary)",
                "product_price": "₹433",
                "product_original_price": "₹483",
                "currency": "INR",
                "product_star_rating": "3.9",
                "product_num_ratings": 3803,
                "product_url": "https://www.amazon.in/dp/B072NBHL7K",
                "product_photo": "https://m.media-amazon.com/images/I/71jXMYdi5FL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹433",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": false
            },
            {
                "asin": "B0CXXD9QNG",
                "product_title": "Lymio Men Shorts || Men Shorts Cotton || Men Shorts Casual (Short)",
                "product_price": "₹499",
                "product_original_price": "₹2,999",
                "currency": "INR",
                "product_star_rating": "3.2",
                "product_num_ratings": 191,
                "product_url": "https://www.amazon.in/dp/B0CXXD9QNG",
                "product_photo": "https://m.media-amazon.com/images/I/61Z4Q9K3bqL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹499",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B079SLJPT1",
                "product_title": "Dennis Lingo Men&#x27;s Solid Slim Fit Cotton Casual Shirt with Spread Collar &amp; Full Sleeves (Also Available in Plus Size)",
                "product_price": "₹584.10",
                "product_original_price": "₹1,849",
                "currency": "INR",
                "product_star_rating": "3.8",
                "product_num_ratings": 38176,
                "product_url": "https://www.amazon.in/dp/B079SLJPT1",
                "product_photo": "https://m.media-amazon.com/images/I/51yIybqYFTL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹584.10",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B07YT1PVNJ",
                "product_title": "Amazon Brand - Symbol Men&#x27;s Stretchable Formal Pants | Trousers (Slim Fit)",
                "product_price": "₹799",
                "product_original_price": "₹2,499",
                "currency": "INR",
                "product_star_rating": "3.7",
                "product_num_ratings": 16509,
                "product_url": "https://www.amazon.in/dp/B07YT1PVNJ",
                "product_photo": "https://m.media-amazon.com/images/I/717-WaIUi9L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹799",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "300+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B00JZM2FS4",
                "product_title": "Rupa Men&#x27;s Vest",
                "product_price": "₹197",
                "product_original_price": "₹306",
                "currency": "INR",
                "product_star_rating": "4.1",
                "product_num_ratings": 4145,
                "product_url": "https://www.amazon.in/dp/B00JZM2FS4",
                "product_photo": "https://m.media-amazon.com/images/I/81Z4r3b0SbL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹197",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": false
            },
            {
                "asin": "B07BTZ8NFL",
                "product_title": "Alan Jones Clothing Men&#x27;s Slim Fit Track pants",
                "product_price": "₹499",
                "product_original_price": "₹1,299",
                "currency": "INR",
                "product_star_rating": "4",
                "product_num_ratings": 17655,
                "product_url": "https://www.amazon.in/dp/B07BTZ8NFL",
                "product_photo": "https://m.media-amazon.com/images/I/81T5bT53BSL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹499",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B0CJ2VKYHY",
                "product_title": "hotfits Men&#x27;s Black &amp; Grey Cotton Regular Shorts - Workout, Gym, Running, Yoga and Sports Shorts - Camouflage Printed - Pack of 2",
                "product_price": "₹499",
                "product_original_price": "₹998",
                "currency": "INR",
                "product_star_rating": "3.9",
                "product_num_ratings": 240,
                "product_url": "https://www.amazon.in/dp/B0CJ2VKYHY",
                "product_photo": "https://m.media-amazon.com/images/I/71AFwWf9LcL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹499",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": false
            },
            {
                "asin": "B0CZ47FHH7",
                "product_title": "Lymio Men Cargo || Men Cargo Pants || Men Cargo Pants Cotton || Cargos for Men (Army)",
                "product_price": "₹699",
                "product_original_price": "₹3,999",
                "currency": "INR",
                "product_star_rating": "3.7",
                "product_num_ratings": 210,
                "product_url": "https://www.amazon.in/dp/B0CZ47FHH7",
                "product_photo": "https://m.media-amazon.com/images/I/61IEV2+5pbL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹699",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "300+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B0D73QWFMY",
                "product_title": "ADDIZ Men&#x27;s Sports Regular Fit Lycra Track Pant with Two Side Pockets",
                "product_price": "₹449",
                "product_original_price": "₹899",
                "currency": "INR",
                "product_star_rating": "3.3",
                "product_num_ratings": 25,
                "product_url": "https://www.amazon.in/dp/B0D73QWFMY",
                "product_photo": "https://m.media-amazon.com/images/I/41wQ6zys+lL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹449",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "100+ bought in past month",
                "delivery": null,
                "has_variations": true
            },
            {
                "asin": "B0CRDBXYF1",
                "product_title": "Lymio Casual Shirt for Men|| Shirt for Men|| Men Stylish Shirt (D-Crush-16-23)",
                "product_price": "₹379",
                "product_original_price": "₹2,999",
                "currency": "INR",
                "product_star_rating": "3.6",
                "product_num_ratings": 2008,
                "product_url": "https://www.amazon.in/dp/B0CRDBXYF1",
                "product_photo": "https://m.media-amazon.com/images/I/81boXIR+s3L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹379",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B07DMYR49H",
                "product_title": "Allen Solly Men&#x27;s Slim Fit Shirt",
                "product_price": "₹869",
                "product_original_price": "₹1,399",
                "currency": "INR",
                "product_star_rating": "3.7",
                "product_num_ratings": 15240,
                "product_url": "https://www.amazon.in/dp/B07DMYR49H",
                "product_photo": "https://m.media-amazon.com/images/I/51T70SlCdbL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹869",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B0CJPVZ9L3",
                "product_title": "ENDEAVOUR WEAR Men&#x27;s Outdoor Quick Dry Lightweight Sports Shorts Zipper Pockets",
                "product_price": "₹398",
                "product_original_price": "₹899",
                "currency": "INR",
                "product_star_rating": "4",
                "product_num_ratings": 1671,
                "product_url": "https://www.amazon.in/dp/B0CJPVZ9L3",
                "product_photo": "https://m.media-amazon.com/images/I/51HDl19KKpL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹398",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B07TLF2NQ8",
                "product_title": "Amazon Brand - Symbol Men&#x27;s Cotton Printed Boxer Shorts (Combo Pack of 2) Casual | Underwear | Half pants | Short Pant - Regular Fit with Back Pocket",
                "product_price": "₹549",
                "product_original_price": "₹1,398",
                "currency": "INR",
                "product_star_rating": "3.9",
                "product_num_ratings": 16090,
                "product_url": "https://www.amazon.in/dp/B07TLF2NQ8",
                "product_photo": "https://m.media-amazon.com/images/I/81N9UZ0wKML._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹549",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B0CM12DJRG",
                "product_title": "Leriya Fashion Textured Shirts for Men || Casual Shirt for Men || Shirt for Men|| Men Stylish Shirt || Men Fancy Shirt || Men Full Sleeve Shirt || Plain Shirts for Men",
                "product_price": "₹449",
                "product_original_price": "₹1,999",
                "currency": "INR",
                "product_star_rating": "3.8",
                "product_num_ratings": 752,
                "product_url": "https://www.amazon.in/dp/B0CM12DJRG",
                "product_photo": "https://m.media-amazon.com/images/I/715Gcc34mvL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹449",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B0713QPGCF",
                "product_title": "Dennis Lingo Men&#x27;s Solid Slim Fit Casual Shirt, Full Sleeve Shirt for Casual Wear &amp; Formal Wear (Also Available in Plus Size)",
                "product_price": "₹499",
                "product_original_price": "₹1,849",
                "currency": "INR",
                "product_star_rating": "3.8",
                "product_num_ratings": 14292,
                "product_url": "https://www.amazon.in/dp/B0713QPGCF",
                "product_photo": "https://m.media-amazon.com/images/I/61qcnAHZP3L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹499",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B09Z78VMW1",
                "product_title": "Levi&#x27;s Men&#x27;s Regular Fit Low-Rise Jeans",
                "product_price": "₹1,484.10",
                "product_original_price": "₹3,199",
                "currency": "INR",
                "product_star_rating": "3.9",
                "product_num_ratings": 1081,
                "product_url": "https://www.amazon.in/dp/B09Z78VMW1",
                "product_photo": "https://m.media-amazon.com/images/I/51OKY3mabbL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹1,484.10",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "300+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "coupon_text": "Save 5% with coupon (limited sizes/colours)",
                "has_variations": true
            },
            {
                "asin": "B0D5MLNQ7M",
                "product_title": "AUSK Men Tshirt || Mens Sports T-Shirts (Color-)",
                "product_price": "₹299",
                "product_original_price": "₹1,499",
                "currency": "INR",
                "product_star_rating": "2.4",
                "product_num_ratings": 8,
                "product_url": "https://www.amazon.in/dp/B0D5MLNQ7M",
                "product_photo": "https://m.media-amazon.com/images/I/616bDUoOBjL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹299",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "100+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B07D4HMLR4",
                "product_title": "XYXX Men&#x27;s Checkmate 100% Super Combed Cotton Casual Style Pyjamas With Dual Side Pockets And No Marks Waistband",
                "product_price": "₹695",
                "product_original_price": "₹799",
                "currency": "INR",
                "product_star_rating": "4",
                "product_num_ratings": 4821,
                "product_url": "https://www.amazon.in/dp/B07D4HMLR4",
                "product_photo": "https://m.media-amazon.com/images/I/71zoEzZDS5L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹695",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "coupon_text": "Save 2% with coupon (limited sizes/colours)",
                "has_variations": true
            },
            {
                "asin": "B0C6Y8F75R",
                "product_title": "JUST RIDER 2 in 1 Running Sports Shorts for Men with Mobile Phone Pocket Light Weight Quick Dry Fabric for Gym Athletic Workout Running Shorts Lightweight Training Yoga Gym Short with Towel Loop",
                "product_price": "₹498",
                "product_original_price": "₹1,499",
                "currency": "INR",
                "product_star_rating": "3.2",
                "product_num_ratings": 269,
                "product_url": "https://www.amazon.in/dp/B0C6Y8F75R",
                "product_photo": "https://m.media-amazon.com/images/I/61Li8F17jKL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹498",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "100+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": false
            },
            {
                "asin": "B07YHXNT8D",
                "product_title": "Raymond Fabrics Makers Men&#x27;s Unstitched Poly Cotton Plain Shirt and Trouser Fabric (Multicolour, Free Size) -Combo Set of 2 Solid",
                "product_price": "₹1,475",
                "product_original_price": "₹2,998",
                "currency": "INR",
                "product_star_rating": "3.9",
                "product_num_ratings": 239,
                "product_url": "https://www.amazon.in/dp/B07YHXNT8D",
                "product_photo": "https://m.media-amazon.com/images/I/71zQrhyOVuL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹1,475",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "100+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": false
            },
            {
                "asin": "B0CG2563J7",
                "product_title": "Bellstone Men Solid Cotton Blend Straight Kurta Shirt",
                "product_price": "₹399",
                "product_original_price": "₹2,499",
                "currency": "INR",
                "product_star_rating": "3.4",
                "product_num_ratings": 526,
                "product_url": "https://www.amazon.in/dp/B0CG2563J7",
                "product_photo": "https://m.media-amazon.com/images/I/61Zjr852N3L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹399",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "100+ bought in past month",
                "delivery": null,
                "has_variations": true
            },
            {
                "asin": "B0CMTXMV4R",
                "product_title": "GRECIILOOKS Mens Casual Poly Lycra Regular Fit Track Pant",
                "product_price": "₹479",
                "product_original_price": "₹1,999",
                "currency": "INR",
                "product_star_rating": "3.9",
                "product_num_ratings": 293,
                "product_url": "https://www.amazon.in/dp/B0CMTXMV4R",
                "product_photo": "https://m.media-amazon.com/images/I/51hpIQa8PuL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹479",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B012SSWGJO",
                "product_title": "Jockey Mens T-Shirt 2714_Pack of 1",
                "product_price": "₹574",
                "product_original_price": "₹579",
                "currency": "INR",
                "product_star_rating": "4.2",
                "product_num_ratings": 21385,
                "product_url": "https://www.amazon.in/dp/B012SSWGJO",
                "product_photo": "https://m.media-amazon.com/images/I/61nEM6mXQVL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹574",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "100+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B01N6WKIVC",
                "product_title": "Euro Men&#x27;s Cotton Brief (Pack of 5) (Colors May Vary)",
                "product_price": "₹494",
                "product_original_price": "₹630",
                "currency": "INR",
                "product_star_rating": "3.8",
                "product_num_ratings": 3960,
                "product_url": "https://www.amazon.in/dp/B01N6WKIVC",
                "product_photo": "https://m.media-amazon.com/images/I/81adovbULeL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 8,
                "product_minimum_offer_price": "₹490",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": false
            },
            {
                "asin": "B07CXQZ5YV",
                "product_title": "U.S. POLO ASSN. Men&#x27;s Regular Fit T-Shirt",
                "product_price": "₹549",
                "product_original_price": "₹749",
                "currency": "INR",
                "product_star_rating": "4",
                "product_num_ratings": 8871,
                "product_url": "https://www.amazon.in/dp/B07CXQZ5YV",
                "product_photo": "https://m.media-amazon.com/images/I/51KSqNXmDjL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹549",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B0D8Y7SPVM",
                "product_title": "MIA FASHION Men&#x27;s Rain Coat, Water Resistant Jacket | Trending Lightweight Windcheater Nylon Jacket | Stylish Full Sleeves Stand Collar for Sports Tracking &amp; Gym Jacket",
                "product_price": "₹799",
                "product_original_price": "₹2,499",
                "currency": "INR",
                "product_star_rating": "1",
                "product_num_ratings": 2,
                "product_url": "https://www.amazon.in/dp/B0D8Y7SPVM",
                "product_photo": "https://m.media-amazon.com/images/I/41oid2WYrKL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹799",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "50+ bought in past month",
                "delivery": null,
                "has_variations": true
            },
            {
                "asin": "B07ZZ5MGY4",
                "product_title": "XYXX Men&#x27;s Ace Super Combed Cotton &amp; Micro Modal Regular Fit Solid Round Neck Vest (Pack of 2)",
                "product_price": "₹445",
                "product_original_price": "₹598",
                "currency": "INR",
                "product_star_rating": "4.2",
                "product_num_ratings": 933,
                "product_url": "https://www.amazon.in/dp/B07ZZ5MGY4",
                "product_photo": "https://m.media-amazon.com/images/I/71PtgncbxPL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹445",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "100+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "coupon_text": "Save 2% with coupon (limited sizes/colours)",
                "has_variations": true
            },
            {
                "asin": "B0CPVNLPDZ",
                "product_title": "Lymio Men Regular Fit Pants",
                "product_price": "₹449",
                "product_original_price": "₹2,999",
                "currency": "INR",
                "product_star_rating": "3.7",
                "product_num_ratings": 643,
                "product_url": "https://www.amazon.in/dp/B0CPVNLPDZ",
                "product_photo": "https://m.media-amazon.com/images/I/61JweMWswjL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹449",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B01N4TUVAD",
                "product_title": "Rupa Jon Men&#x27;s Cotton Vest (Pack of 3)",
                "product_price": "₹364",
                "product_original_price": "₹411",
                "currency": "INR",
                "product_star_rating": "4",
                "product_num_ratings": 9492,
                "product_url": "https://www.amazon.in/dp/B01N4TUVAD",
                "product_photo": "https://m.media-amazon.com/images/I/71UKBLjGDyL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 7,
                "product_minimum_offer_price": "₹255",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": false,
                "climate_pledge_friendly": false,
                "sales_volume": "100+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": false
            },
            {
                "asin": "B076CR4HPR",
                "product_title": "Urbano Fashion Men&#x27;s Slim Fit Washed Jeans Stretchable",
                "product_price": "₹601",
                "product_original_price": "₹1,399",
                "currency": "INR",
                "product_star_rating": "3.6",
                "product_num_ratings": 9290,
                "product_url": "https://www.amazon.in/dp/B076CR4HPR",
                "product_photo": "https://m.media-amazon.com/images/I/61cxmVOEihL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹601",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "100+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B072KS6RDS",
                "product_title": "LUX VENUS Men&#x27;s Cotton Vest (Pack of 6)",
                "product_price": "₹599",
                "product_original_price": "₹661",
                "currency": "INR",
                "product_star_rating": "3.9",
                "product_num_ratings": 15165,
                "product_url": "https://www.amazon.in/dp/B072KS6RDS",
                "product_photo": "https://m.media-amazon.com/images/I/81PaKtEAIZL._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 3,
                "product_minimum_offer_price": "₹598",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "100+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": false
            },
            {
                "asin": "B07R4NJ1QJ",
                "product_title": "Van Heusen Men&#x27;s Regular Fit Polo T-Shirt",
                "product_price": "₹980",
                "product_original_price": "₹1,129",
                "currency": "INR",
                "product_star_rating": "4.1",
                "product_num_ratings": 4011,
                "product_url": "https://www.amazon.in/dp/B07R4NJ1QJ",
                "product_photo": "https://m.media-amazon.com/images/I/71af25JeJ1L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹980",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "100+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            },
            {
                "asin": "B0CVN77CHW",
                "product_title": "POSHAX Track Pant for Men || Track Pants || Plain Track Pant (TP-20-24)",
                "product_price": "₹509",
                "product_original_price": "₹4,999",
                "currency": "INR",
                "product_star_rating": "4.2",
                "product_num_ratings": 284,
                "product_url": "https://www.amazon.in/dp/B0CVN77CHW",
                "product_photo": "https://m.media-amazon.com/images/I/51ZSDQccH5L._AC_UL960_FMwebp_QL65_.jpg",
                "product_num_offers": 1,
                "product_minimum_offer_price": "₹509",
                "is_best_seller": true,
                "is_amazon_choice": false,
                "is_prime": true,
                "climate_pledge_friendly": false,
                "sales_volume": "200+ bought in past month",
                "delivery": "FREE Delivery by Amazon",
                "has_variations": true
            }
        ]
    }
}
{
    "asin": "B0CZDY1ZKX",
    "product_title": "Boldfit Sports T Shirt for Men Quick Dry Fit Tshirt for Men Gym T Shirts for Men for Casual Wear Workout T Shirts for Man Active Gym Wear for Men Running T-Shirts for Men T Shirt for Man",
    "product_price": "₹399",
    "product_original_price": "₹999",
    "currency": "INR",
    "product_star_rating": "4.8",
    "product_num_ratings": 74,
    "product_url": "https://www.amazon.in/dp/B0CZDY1ZKX",
    "product_photo": "https://m.media-amazon.com/images/I/61zfo184NoL._AC_UL960_FMwebp_QL65_.jpg",
    "product_num_offers": 1,
    "product_minimum_offer_price": "₹399",
    "is_best_seller": true,
    "is_amazon_choice": false,
    "is_prime": false,
    "climate_pledge_friendly": false,
    "sales_volume": "200+ bought in past month",
    "delivery": "FREE Delivery by Amazon",
    "has_variations": true
}
let arr = responseDto.data.products;

arr.map((e)=>{
    console.log(e.product_title);
    console.log("INR"+e.product_price);
    console.log(e.product_original_price);
    console.log(e.product_star_rating);
    console.log(e.product_url);
    console.log(e.product_photo);
    console.log(e.delivery);
})